language: go
go:
  - 1.11.x
sudo: false
install:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - export GO111MODULE=on
  - go build
  - (cd cmd/miner && go build)
  - ./run_tests.sh
